//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_Part_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OrganizationEntities : DbContext
    {
        public OrganizationEntities()
            : base("name=OrganizationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Dept> tbl_Dept { get; set; }
        public virtual DbSet<tbl_Emp> tbl_Emp { get; set; }
    
        public virtual ObjectResult<SP_GetAllEmployee_Result> SP_GetAllEmployee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetAllEmployee_Result>("SP_GetAllEmployee");
        }
    
        public virtual ObjectResult<SP_GetEmployeesByDid_Result> SP_GetEmployeesByDid(Nullable<int> did)
        {
            var didParameter = did.HasValue ?
                new ObjectParameter("Did", did) :
                new ObjectParameter("Did", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetEmployeesByDid_Result>("SP_GetEmployeesByDid", didParameter);
        }
    
        public virtual int SP_GetEmpNameAndSalaryByEid(Nullable<int> eid, ObjectParameter eName, ObjectParameter eSal)
        {
            var eidParameter = eid.HasValue ?
                new ObjectParameter("Eid", eid) :
                new ObjectParameter("Eid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GetEmpNameAndSalaryByEid", eidParameter, eName, eSal);
        }
    }
}
